/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "GroupsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MessagesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TeamsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
